sudo: false
dist: trusty
language: java
jdk:
- oraclejdk8
install: ./installViaTravis.sh
script: ./buildViaTravis.sh
env:
  global:
  - secure: H5Gre2D7TjPp0UzMgWAlH6m/MifDk0JEQPTLU1Qr+Dm6fBSfozjYs1y29hk9beM936IDGdihYPRon6t1ZNWX1vQKGrmva2ynMwXs12y/F6GEEgjLRVLpX+JAfANZzVDcnIhdWEb8mWQ4ESh0+i2mOMJFwWFhGy2WQuobHCkrn3E=
  - secure: eFCW3J9zX0eNMk1PCHGy4EXFGp5PiozIyvO6SB2kna0Jt6CdY3UA/STgpRtReT1iTW/C/lyYb+h6H8FISvTkJhVKITDoVcOpwUXCYxQdXEvhL633z9LYQcKexricKzP2hpePcmEGmNcVNxn9mrIRdo28ds4XOT7dpU54+ZmLTpU=
  - secure: T3ROxa73aSSYdwjPJUzjqkMjxHV+g4scdI5pJzTIsQ3fwaoZ3cPubLPOy2pYx59a4MhpdNuT1or/yr/khToPYHxHgj9pGZ8JHLRYjzEEmfDj2WyhVWeYC88Q+4Ncc2JSMT5lHKS/j+N3R9pZf/Cuy9keyvLEKQlXBOBPBf7MWcc=
  - secure: fIXSx1SIXJF8//Qo9zmLWKn+APW1sYxw8V1U47kfQTw3Ks2RTg8J7z7gdP4YObWrrrMjZgtCJOWolCNdCPJd8bxypv8o4YAw4w/nDrs/m7p0HcIirZypEGWYuju3g1JkZzQkvCIXIYMfHL0jlYMvjsY9Pjn5rgpFGqEW6lloOCE=
cache:
  directories:
  - $HOME/.gradle/caches
